### ISSUE TITLE
No url found for submodule path 'packpack' in .gitmodules

### ISSUE THREAD

**Issue by Totktonada** [racherb/watcher#9]
It seems, there is no `.gitmodules` file in the repository.

How to reproduce:

```sh
$ git clone git@github.com:racherb/watcher.git
<...>
$ git submodule update --recursive --init
fatal: No url found for submodule path 'packpack' in .gitmodules
```

**Comment by racherb** [comment]
Indeed @Totktonada , by executing:

`$ git submodule status`

I get:

`
$ fatal: no submodule mapping found in .gitmodules for path 'packpack'.`

The reason is that "_packpack_" must not be in the git repository. 
I have removed it, please try again and let me know.

Feel free to generate some PR if you consider it appropriate.
